### PR TITLE
Additional platforms

### PR DESCRIPTION
**Pull request by itslazyvar**

### CODE REVIEW

**Comment by GeekyDeaks** [comment]
Nice!  This mean you are happy with people updating their own details?  

I am just testing the latest version of discord.js so will push these changes at the same time.  I'll also make the games bit work properly.

**Comment by GeekyDeaks** [comment]
One tip LMG.  You should be able to specify a different branch to `master` when you submit the pull request.  If you think you will be making more changes and worried about messing up `master` then I'll make an `indev` branch for us to use.  This does mean you have to think about which branches you are working on with your instance of the bot though.

**Comment by itslazyvar** [comment]
Thanks for the heads up. I have yet to come up with a good way to manage different versions and instances, but perhaps you can give me some tips on that next year ;)

**Comment by GeekyDeaks** [comment]
You have triggered my OCD 😄 

This is not very well optimised and there are 2 other commands that display the member information - `gamer` and `players`.  At present they just kick out the XBL and PSN, but I guess they should either all use some common function to display or we repeat the code in each command module.

**Pull request merged**
