### PR TITLE
Destiny advisor

### PR DESCRIPTION
**Pull request by unisys12**
Added Daily Story and partial Trials support _(need to finish resolving some hashes) for Issue #16 . Also, removed the image due to possible data issues that might arise for mobile users. Neat feature, but not worth the extra data usage that the end user would/might incur.

### CODE REVIEW

**Comment by GeekyDeaks** [comment]
Hey @unisys12 - nice work - I have resolved the conflict and wanted to see if you minded me doing a bit of work on this too?

I was thinking of taking the `if` statements and making them into a `switch` statement and then farming out the specific reports into their own functions so that you can do say `advisor daily` and it shows you all the daily activities, or `advisor ds` / `story` / `dailystory` to get just the daily story.  What do you think?

**Comment by unisys12** [comment]
Switch is exactly where I wanted to go, but my poor little brain got side tracked and flipped upside down. Absolutely dude. Knock yourself out.

Initially, that was my thought as well and planned on writing out individual methods for each of the 14 categories, then assembling a switch statement that would assemble them into exactly what you describe. but.... yeah. I think what happened was I decided to get a few different methods working and then reformat into the above. 

With Trials back on, I am going to resolve the Bounty and Reward Hashes, if you don't first. But, that top of my priority list.

**Comment by GeekyDeaks** [comment]
messed around with the formatting a little and had it outputting all the modifiers/rewards for the weekly strike / nightfall and daily chapter.  Not been able to find the trials items in the hash though.

**Comment by unisys12** [comment]
I will investigate the Trials Hashes. IIRC, that was why I left them they way they were, at the time, just displaying the hashes. Next step was to hunt them down.

**Pull request merged**
